import { ActionButton, Card, ErrorText, LinkButton, OrderPage, StatusBadge, money, prettySlot } from "@/components/OrderUI";
import { colors } from "@/constants/colors";
import { useOrders } from "@/hooks/useOrders";
import type { Order } from "@/types/order";
import { Image } from "expo-image";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

export default function MyOrders() {
  const { orders, loading, error, reload, reloadOrders, reorder } = useOrders();
  useEffect(() => { void reloadOrders(); }, [reloadOrders]);
  const [tab, setTab] = useState<"active" | "past">("active");
  const filtered = orders.filter(order => tab === "active" ? !["collected", "cancelled"].includes(order.status) : ["collected", "cancelled"].includes(order.status));
  const buyAgain = (order: Order) => { reorder(order); router.push("/(customer)/cart"); };
  return <OrderPage title="My orders" eyebrow="YOUR GRAB & GO JOURNEY" nav>
    <ErrorText message={error} />
    <Card dark><Text style={styles.heroTitle}>Everything in one place.</Text><Text style={styles.heroCopy}>Follow your pickup, revisit a basket, or see what you bought before.</Text></Card>
    <View style={styles.tabs}><Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === "active" }} onPress={() => setTab("active")} style={[styles.tab, tab === "active" && styles.tabActive]}><Text style={[styles.tabText, tab === "active" && styles.tabTextActive]}>Active ({orders.filter(item => !["collected", "cancelled"].includes(item.status)).length})</Text></Pressable><Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === "past" }} onPress={() => setTab("past")} style={[styles.tab, tab === "past" && styles.tabActive]}><Text style={[styles.tabText, tab === "past" && styles.tabTextActive]}>Past ({orders.filter(item => ["collected", "cancelled"].includes(item.status)).length})</Text></Pressable></View>
    {loading ? <Card><Text style={styles.empty}>Loading your orders…</Text></Card> : filtered.length ? filtered.map(order => <Card key={order.id}><View style={styles.cardHead}><View style={{ flex: 1 }}><Text style={styles.shop}>{order.shop.name}</Text><Text style={styles.reference}>{order.reference}</Text></View><StatusBadge status={order.status} /></View><Text style={styles.meta}>Pickup · {prettySlot(order.draft.pickupSlot)}</Text><View style={styles.preview}>{order.items.slice(0, 4).map(item => <Image key={item.product.id} source={item.product.image} contentFit="cover" style={styles.previewImage} accessibilityLabel={item.product.name} />)}<Text style={styles.itemCount}>{order.items.reduce((sum, item) => sum + item.quantity, 0)} items</Text><Text style={styles.total}>{money(order.total)}</Text></View><View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(customer)/order-details", params: { id: order.id } })} style={styles.detailsButton}><Text style={styles.detailsText}>Details</Text></Pressable>{order.status !== "cancelled" && order.status !== "collected" ? <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(customer)/order-tracking", params: { id: order.id } })} style={styles.trackButton}><Text style={styles.trackText}>Track order  →</Text></Pressable> : <Pressable accessibilityRole="button" onPress={() => buyAgain(order)} style={styles.trackButton}><Text style={styles.trackText}>Reorder  →</Text></Pressable>}</View></Card>) : <Card><View style={styles.emptyWrap}><Text style={styles.emptyTitle}>{tab === "active" ? "No active orders" : "No past orders yet"}</Text><Text style={styles.empty}>{tab === "active" ? "Your next pickup will appear here as soon as you place an order." : "Collected and cancelled orders will appear here."}</Text><ActionButton label="Browse your cart" light onPress={() => router.push("/(customer)/cart")} /></View></Card>}
    {error ? <LinkButton label="Retry loading orders" onPress={() => { void reload(); }} /> : null}
  </OrderPage>;
}
const styles = StyleSheet.create({ heroTitle: { color: colors.white, fontSize: 19, fontWeight: "800" }, heroCopy: { color: "#D8D6EB", fontSize: 12, lineHeight: 19, marginTop: 7 }, tabs: { flexDirection: "row", backgroundColor: colors.lilac, padding: 4, borderRadius: 14 }, tab: { flex: 1, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 11 }, tabActive: { backgroundColor: colors.white }, tabText: { color: colors.muted, fontSize: 12, fontWeight: "700" }, tabTextActive: { color: colors.ink, fontWeight: "900" }, cardHead: { flexDirection: "row", alignItems: "center" }, shop: { color: colors.ink, fontSize: 15, fontWeight: "900" }, reference: { color: colors.muted, fontSize: 10, marginTop: 4 }, meta: { color: colors.muted, fontSize: 11, marginTop: 13 }, preview: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 15 }, previewImage: { width: 37, height: 37, borderRadius: 9, backgroundColor: colors.lilac }, itemCount: { color: colors.muted, fontSize: 11, marginLeft: 5, flex: 1 }, total: { color: colors.ink, fontSize: 14, fontWeight: "900" }, actions: { flexDirection: "row", gap: 9, marginTop: 15 }, detailsButton: { flex: 1, minHeight: 44, alignItems: "center", justifyContent: "center", borderColor: colors.line, borderWidth: 1, borderRadius: 12 }, detailsText: { color: colors.ink, fontSize: 12, fontWeight: "800" }, trackButton: { flex: 1.4, minHeight: 44, alignItems: "center", justifyContent: "center", backgroundColor: colors.ink, borderRadius: 12 }, trackText: { color: colors.white, fontSize: 12, fontWeight: "800" }, emptyWrap: { alignItems: "center", gap: 13, paddingVertical: 18 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, empty: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center" } });
